version: '3.8'

services:
  gscores-frontend:
    build: .
    container_name: gscores_web
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    restart: always