version: '3.8'

services:
  gscores-frontend:
    build: .
    container_name: gscores_web
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=https://gscores-1-y91m.onrender.com/api
    restart: always